output "cluster_name" {
  description = "EKS cluster name"
  value       = aws_eks_cluster.main_cluster.name
}

output "cluster_endpoint" {
  description = "EKS cluster endpoint URL"
  value       = aws_eks_cluster.main_cluster.endpoint
}

output "eks_oidc_provider_url" {
  description = "The OIDC issuer URL automatically generated by the EKS cluster, used for configuring IAM Roles for Service Accounts (IRSA)."
  value       = aws_eks_cluster.main_cluster.identity[0].oidc[0].issuer
}